version: '3'

services:
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    environment:
      - CONSUL_BIND_INTERFACE=eth0

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  facade-service:
    build:
      context: ./facade-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - consul
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500

  logging-service-1:
    build:
      context: ./logging-service
    ports:
      - "8081:8081"
      - "9090:9090"
    depends_on:
      - consul
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8081
      - GRPC_SERVER_PORT=9090
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500

  logging-service-2:
    build:
      context: ./logging-service
    ports:
      - "8082:8082"
      - "9091:9091"
    depends_on:
      - consul
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8082
      - GRPC_SERVER_PORT=9091
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500

  logging-service-3:
    build:
      context: ./logging-service
    ports:
      - "8083:8083"
      - "9093:9093"
    depends_on:
      - consul
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8083
      - GRPC_SERVER_PORT=9093
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500

  message-service-1:
    build:
      context: ./message-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
      - consul
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8084
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500

  message-service-2:
    build:
      context: ./message-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka
      - consul
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8085
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
