version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  config-server:
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  facade-service:
    build:
      context: ./facade-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - CONFIG_SERVER_URL=http://config-server:8888

  logging-service-1:
    build:
      context: ./logging-service
    ports:
      - "8081:8081"
      - "9090:9090"
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8081

  message-service-1:
    build:
      context: ./message-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8082
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - CONFIG_SERVER_URL=http://config-server:8888

  message-service-2:
    build:
      context: ./message-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8083
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - CONFIG_SERVER_URL=http://config-server:8888