
server:
    port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
resilience4j:
    circuitbreaker:
        instances:
          message-service:
              slidingWindowSize: 10
              minimumNumberOfCalls: 5
              failureRateThreshold: 50
              waitDurationInOpenState: 10000
              permittedNumberOfCallsInHalfOpenState: 3
          logging-service:
              slidingWindowSize: 10
              minimumNumberOfCalls: 5
              failureRateThreshold: 50
              waitDurationInOpenState: 10000
              permittedNumberOfCallsInHalfOpenState: 3
