spring:
  application:
    name: facade-service
  cloud:
    consul:
      host: ${CONSUL_HOST:consul}
      port: ${CONSUL_PORT:8500}
      discovery:
        instanceId: ${spring.application.name}:${server.port}
        serviceName: ${spring.application.name}
        register: true
        registerHealthCheck: true
        healthCheckPath: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

server:
  port: 8080

resilience4j:
  retry:
    instances:
      logging-service:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  circuitbreaker:
    instances:
      logging-service:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

config:
  server:
    url: http://localhost:8888