spring:
  application:
    name: config-server

server:
  port: 8888

services:
  map:
    logging-service:
      host: ${LOGGING_SERVICE_HOST:localhost}
      grpcPorts:
        - 9090
        - 9091
        - 9093
      restPorts:
        - 8081
        - 8082
        - 8083

    message-service:
      host: ${MESSAGE_SERVICE_HOST:localhost}
      restPorts:
        - 8084
        - 8085