spring:
  application:
    name: config-server

server:
  port: 8888

services:
  map:
    logging-service:
      host: localhost
      grpcPorts:
        - 9090
      restPorts:
        - 8081

    message-service:
      host: localhost
      restPorts:
        - 8084
        - 8085